package views;

import controller.ServiceController;
import dto.PlayerDTO;
import java.awt.Color;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import util.DateUtils;

/**
 *
 * @author Flavio Morais
 */
public class ViewPowers extends javax.swing.JFrame {

    ServiceController controller = new  ServiceController();
    
    Integer idMatch, typeMatch, idPlayer1, idPlayer2;
    String selectedPower;
    PlayerDTO player1, player2;
    boolean fimDeJogo = false;
    List<JRadioButton> powerList;
    LocalDateTime start;
    
    public ViewPowers() {
        initComponents();
    }
    
    public ViewPowers(int idMatch, int typeMatch, int idPlayer1, int idPlayer2, LocalDateTime inicio) {
        initComponents();
        this.idMatch = idMatch;
        this.typeMatch = typeMatch;
        this.idPlayer1 = idPlayer1;
        this.idPlayer2 = idPlayer2;
        this.player1 = controller.findPlayerById(this.idPlayer1);
        this.player2 = controller.findPlayerById(this.idPlayer2);
        this.start = DateUtils.removeHorarioVeraoIndevido(inicio);
        
        btnPlayer1.setText(player1.getName());
        btnPlayer2.setText(player2.getName());
        
        this.powerList = Arrays.asList(btnBoost, btnStickyGoo, btnBlock, btnRamp, btnBeachBall,
                    btnSwapGoals, btnGhosted, btnBigHead, btnBigBumper, btnMoveBall, btnMovePlayer);
        this.powerList.forEach(pwr -> pwr.setUI(null));
        
        txtGolPlayer1.setText("0");
        txtGolPlayer2.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPower = new javax.swing.ButtonGroup();
        btnBeachBall = new javax.swing.JRadioButton();
        btnBigBumper = new javax.swing.JRadioButton();
        btnBigHead = new javax.swing.JRadioButton();
        btnBlock = new javax.swing.JRadioButton();
        btnBoost = new javax.swing.JRadioButton();
        btnGhosted = new javax.swing.JRadioButton();
        btnMoveBall = new javax.swing.JRadioButton();
        btnMovePlayer = new javax.swing.JRadioButton();
        btnRamp = new javax.swing.JRadioButton();
        btnStickyGoo = new javax.swing.JRadioButton();
        btnSwapGoals = new javax.swing.JRadioButton();
        btnEnviar = new javax.swing.JButton();
        btnFimDeJogo = new javax.swing.JButton();
        txtGolPlayer2 = new javax.swing.JLabel();
        txtGolPlayer1 = new javax.swing.JLabel();
        btnGol = new javax.swing.JButton();
        btnPlayer1 = new javax.swing.JButton();
        btnPlayer2 = new javax.swing.JButton();
        isUsado = new javax.swing.JButton();
        isSucesso = new javax.swing.JButton();
        isGolContra = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(707, 590));
        setResizable(false);
        getContentPane().setLayout(null);

        bgPower.add(btnBeachBall);
        btnBeachBall.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 3, true));
        btnBeachBall.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBeachBall.setOpaque(false);
        btnBeachBall.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnBeachBall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBeachBallMousePressed(evt);
            }
        });
        getContentPane().add(btnBeachBall);
        btnBeachBall.setBounds(460, 170, 220, 100);

        bgPower.add(btnBigBumper);
        btnBigBumper.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 3, true));
        btnBigBumper.setContentAreaFilled(false);
        btnBigBumper.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBigBumper.setFocusPainted(false);
        btnBigBumper.setFocusable(false);
        btnBigBumper.setHideActionText(true);
        btnBigBumper.setRolloverIcon(null);
        btnBigBumper.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnBigBumper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBigBumperMousePressed(evt);
            }
        });
        getContentPane().add(btnBigBumper);
        btnBigBumper.setBounds(30, 70, 210, 100);

        bgPower.add(btnBigHead);
        btnBigHead.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 3, true));
        btnBigHead.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBigHead.setOpaque(false);
        btnBigHead.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnBigHead.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBigHeadMousePressed(evt);
            }
        });
        getContentPane().add(btnBigHead);
        btnBigHead.setBounds(460, 270, 220, 110);

        bgPower.add(btnBlock);
        btnBlock.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 3, true));
        btnBlock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBlock.setHideActionText(true);
        btnBlock.setOpaque(false);
        btnBlock.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnBlock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBlockMousePressed(evt);
            }
        });
        getContentPane().add(btnBlock);
        btnBlock.setBounds(30, 170, 210, 100);

        bgPower.add(btnBoost);
        btnBoost.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 3, true));
        btnBoost.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBoost.setOpaque(false);
        btnBoost.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnBoost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBoostMousePressed(evt);
            }
        });
        getContentPane().add(btnBoost);
        btnBoost.setBounds(30, 380, 210, 110);

        bgPower.add(btnGhosted);
        btnGhosted.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 3, true));
        btnGhosted.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGhosted.setOpaque(false);
        btnGhosted.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnGhosted.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGhostedMousePressed(evt);
            }
        });
        getContentPane().add(btnGhosted);
        btnGhosted.setBounds(240, 270, 220, 110);

        bgPower.add(btnMoveBall);
        btnMoveBall.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 3, true));
        btnMoveBall.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMoveBall.setOpaque(false);
        btnMoveBall.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMoveBall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMoveBallMousePressed(evt);
            }
        });
        getContentPane().add(btnMoveBall);
        btnMoveBall.setBounds(240, 71, 220, 100);

        bgPower.add(btnMovePlayer);
        btnMovePlayer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 3, true));
        btnMovePlayer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMovePlayer.setOpaque(false);
        btnMovePlayer.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMovePlayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMovePlayerMousePressed(evt);
            }
        });
        getContentPane().add(btnMovePlayer);
        btnMovePlayer.setBounds(460, 70, 220, 100);

        bgPower.add(btnRamp);
        btnRamp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 3, true));
        btnRamp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRamp.setOpaque(false);
        btnRamp.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRamp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRampMousePressed(evt);
            }
        });
        getContentPane().add(btnRamp);
        btnRamp.setBounds(240, 171, 220, 100);

        bgPower.add(btnStickyGoo);
        btnStickyGoo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 3, true));
        btnStickyGoo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStickyGoo.setHideActionText(true);
        btnStickyGoo.setOpaque(false);
        btnStickyGoo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnStickyGoo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnStickyGooMousePressed(evt);
            }
        });
        getContentPane().add(btnStickyGoo);
        btnStickyGoo.setBounds(240, 380, 220, 110);

        bgPower.add(btnSwapGoals);
        btnSwapGoals.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 3, true));
        btnSwapGoals.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSwapGoals.setOpaque(false);
        btnSwapGoals.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnSwapGoals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSwapGoalsMousePressed(evt);
            }
        });
        getContentPane().add(btnSwapGoals);
        btnSwapGoals.setBounds(30, 270, 210, 110);

        btnEnviar.setBorderPainted(false);
        btnEnviar.setContentAreaFilled(false);
        btnEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar);
        btnEnviar.setBounds(510, 500, 150, 40);

        btnFimDeJogo.setBorderPainted(false);
        btnFimDeJogo.setContentAreaFilled(false);
        btnFimDeJogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFimDeJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFimDeJogoActionPerformed(evt);
            }
        });
        getContentPane().add(btnFimDeJogo);
        btnFimDeJogo.setBounds(40, 500, 170, 40);

        txtGolPlayer2.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        txtGolPlayer2.setForeground(new java.awt.Color(173, 83, 74));
        txtGolPlayer2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtGolPlayer2.setText("0");
        getContentPane().add(txtGolPlayer2);
        txtGolPlayer2.setBounds(380, 10, 50, 50);

        txtGolPlayer1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        txtGolPlayer1.setForeground(new java.awt.Color(173, 83, 74));
        txtGolPlayer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtGolPlayer1.setText("0");
        getContentPane().add(txtGolPlayer1);
        txtGolPlayer1.setBounds(280, 10, 50, 50);

        btnGol.setFont(new java.awt.Font("Trebuchet MS", 1, 22)); // NOI18N
        btnGol.setForeground(new java.awt.Color(173, 83, 74));
        btnGol.setBorderPainted(false);
        btnGol.setContentAreaFilled(false);
        btnGol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGol.setFocusPainted(false);
        btnGol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGolActionPerformed(evt);
            }
        });
        getContentPane().add(btnGol);
        btnGol.setBounds(270, 490, 170, 60);

        btnPlayer1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        btnPlayer1.setForeground(new java.awt.Color(173, 83, 74));
        btnPlayer1.setToolTipText("");
        btnPlayer1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 3, true));
        btnPlayer1.setBorderPainted(false);
        btnPlayer1.setContentAreaFilled(false);
        btnPlayer1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlayer1.setFocusPainted(false);
        btnPlayer1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnPlayer1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPlayer1.setMaximumSize(new java.awt.Dimension(260, 50));
        btnPlayer1.setMinimumSize(new java.awt.Dimension(50, 50));
        btnPlayer1.setPreferredSize(new java.awt.Dimension(50, 50));
        btnPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlayer1);
        btnPlayer1.setBounds(25, 10, 250, 50);

        btnPlayer2.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        btnPlayer2.setForeground(new java.awt.Color(173, 83, 74));
        btnPlayer2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 0), 3, true));
        btnPlayer2.setBorderPainted(false);
        btnPlayer2.setContentAreaFilled(false);
        btnPlayer2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlayer2.setFocusPainted(false);
        btnPlayer2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPlayer2.setMaximumSize(new java.awt.Dimension(260, 50));
        btnPlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlayer2);
        btnPlayer2.setBounds(433, 10, 250, 50);

        isUsado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 3, true));
        isUsado.setBorderPainted(false);
        isUsado.setContentAreaFilled(false);
        isUsado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isUsadoActionPerformed(evt);
            }
        });
        getContentPane().add(isUsado);
        isUsado.setBounds(500, 390, 150, 30);

        isSucesso.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 3, true));
        isSucesso.setBorderPainted(false);
        isSucesso.setContentAreaFilled(false);
        isSucesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isSucessoActionPerformed(evt);
            }
        });
        getContentPane().add(isSucesso);
        isSucesso.setBounds(500, 420, 150, 30);

        isGolContra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 3, true));
        isGolContra.setBorderPainted(false);
        isGolContra.setContentAreaFilled(false);
        isGolContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isGolContraActionPerformed(evt);
            }
        });
        getContentPane().add(isGolContra);
        isGolContra.setBounds(500, 450, 150, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/booble_main.png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(800, 600));
        jLabel3.setMinimumSize(new java.awt.Dimension(800, 600));
        jLabel3.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 710, 560);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        Integer idPlayer = idPlayerBySelection();
        String namePlayer = namePlayerBySelection();
        Integer idPower;
        
        if (Objects.nonNull(idPlayer)) {
            idPower = controller.findIdByPower(this.selectedPower);
            controller.insertPower(idPlayer, idPower, this.idMatch, isUsado.isBorderPainted(),
                    isSucesso.isBorderPainted(), isGolContra.isBorderPainted());

            StringBuilder message = new StringBuilder(namePlayer + " enviou o poder " + this.selectedPower);
            if (isUsado.isBorderPainted()) {
                message.append(" (usado");
                if (isSucesso.isBorderPainted())
                    message.append(" com sucesso)");
                else if (isGolContra.isBorderPainted())
                    message.append(" com gol contra)");
                else
                    message.append(")");
            } else {
                message.append(" (sem uso)");
            }

            isUsado.setBorderPainted(false);
            isSucesso.setBorderPainted(false);
            isGolContra.setBorderPainted(false);
            JOptionPane.showMessageDialog(rootPane, message.toString());
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione o player!");
        }
    }//GEN-LAST:event_btnEnviarActionPerformed
      
    private Integer idPlayerBySelection() {
        return btnPlayer1.isBorderPainted() ? this.idPlayer1 :
                btnPlayer2.isBorderPainted() ? this.idPlayer2 : null;
    }
    
    private void btnFimDeJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFimDeJogoActionPerformed
        int scoreP1 = Integer.parseInt(txtGolPlayer1.getText());
        int scoreP2 = Integer.parseInt(txtGolPlayer2.getText());
        String message = this.player1.getName() + "  " + scoreP1 + " x " + scoreP2 + "  " + this.player2.getName();
        
        if (JOptionPane.showOptionDialog(rootPane, message, "Fim de jogo", JOptionPane.YES_NO_OPTION,
                JOptionPane.PLAIN_MESSAGE, null, new Object[]{"Fim de Jogo", "Cancelar"}, null) == 0) {
            int pts1 = 1;
            int pts2 = 1;

            if (scoreP1 > scoreP2) {
                pts1 = 3;
                pts2 = 0;
            } else if (scoreP1 < scoreP2) {
                pts1 = 0;
                pts2 = 3;
            }
            controller.insertEndMatch(this.idMatch);
            controller.insertResult(this.idMatch, this.idPlayer1, this.idPlayer2, scoreP1, scoreP2, pts1, pts2);
            new ViewBuscaMatches().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnFimDeJogoActionPerformed

    private void btnGolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGolActionPerformed
        if (!fimDeJogo) {
            String namePlayer = namePlayerBySelection();
            if (Objects.nonNull(namePlayer)) {
                JLabel txtGol = golPlayerBySelection();
                int score = Integer.parseInt(txtGol.getText());

                if (score < this.typeMatch) {
                    if (JOptionPane.showOptionDialog(rootPane, "Gol de " + namePlayer + "?", "GOOOOOOLLL",
                            JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, null,
                            new Object[]{"GOL", "Cancelar"}, null) == 0) {
                        score++;
                        txtGol.setText(String.valueOf(score));
                        controller.insertGoalTime(this.idMatch, idPlayerBySelection(), this.start);
                        if (score == this.typeMatch) {
                            JOptionPane.showMessageDialog(rootPane, "Fim de jogo");
                            btnGol.setBackground(Color.decode("#FEF8D2"));
                            btnGol.setText("Fim de Jogo");
                            btnGol.setContentAreaFilled(true);                    
                            btnGol.setCursor(java.awt.Cursor.getDefaultCursor());
                        }
                    }
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Selecione o player!");
            }
        }
    }//GEN-LAST:event_btnGolActionPerformed

    private String namePlayerBySelection() {
        return btnPlayer1.isBorderPainted() ? this.player1.getName() :
                btnPlayer2.isBorderPainted() ? this.player2.getName() : null;
    }
    
    private JLabel golPlayerBySelection() {
        return btnPlayer1.isBorderPainted() ? txtGolPlayer1 :
                btnPlayer2.isBorderPainted() ? txtGolPlayer2 : null;
    }
    
    private void btnPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer2ActionPerformed
        btnPlayer2.setBorderPainted(true);
        btnPlayer1.setBorderPainted(false);
    }//GEN-LAST:event_btnPlayer2ActionPerformed

    private void isUsadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isUsadoActionPerformed
        isUsado.setBorderPainted(!isUsado.isBorderPainted());
        if (!isUsado.isBorderPainted()) {
            isSucesso.setBorderPainted(false);
            isGolContra.setBorderPainted(false);
        }
    }//GEN-LAST:event_isUsadoActionPerformed

    private void isSucessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isSucessoActionPerformed
        isSucesso.setBorderPainted(!isSucesso.isBorderPainted());
        if (isSucesso.isBorderPainted())
            isUsado.setBorderPainted(true);
        isGolContra.setBorderPainted(false);
    }//GEN-LAST:event_isSucessoActionPerformed

    private void isGolContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isGolContraActionPerformed
        isGolContra.setBorderPainted(!isGolContra.isBorderPainted());
        if (isGolContra.isBorderPainted())
            isUsado.setBorderPainted(true);
        isSucesso.setBorderPainted(false);
    }//GEN-LAST:event_isGolContraActionPerformed

    private void btnPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer1ActionPerformed
        btnPlayer1.setBorderPainted(true);
        btnPlayer2.setBorderPainted(false);
    }//GEN-LAST:event_btnPlayer1ActionPerformed

    private void btnBigBumperMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBigBumperMousePressed
        paintBorder((JRadioButton) evt.getSource(), "Big Bumpers");
    }//GEN-LAST:event_btnBigBumperMousePressed

    private void btnMoveBallMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoveBallMousePressed
        paintBorder((JRadioButton) evt.getSource(), "Move Ball");
    }//GEN-LAST:event_btnMoveBallMousePressed

    private void btnMovePlayerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMovePlayerMousePressed
        paintBorder((JRadioButton) evt.getSource(), "Move Player");
    }//GEN-LAST:event_btnMovePlayerMousePressed

    private void btnBlockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBlockMousePressed
        paintBorder((JRadioButton) evt.getSource(), "Block");
    }//GEN-LAST:event_btnBlockMousePressed

    private void btnRampMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRampMousePressed
        paintBorder((JRadioButton) evt.getSource(), "Ramp");
    }//GEN-LAST:event_btnRampMousePressed

    private void btnBeachBallMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBeachBallMousePressed
        paintBorder((JRadioButton) evt.getSource(), "Beach Ball");
    }//GEN-LAST:event_btnBeachBallMousePressed

    private void btnSwapGoalsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSwapGoalsMousePressed
        paintBorder((JRadioButton) evt.getSource(), "Swap Goals");
    }//GEN-LAST:event_btnSwapGoalsMousePressed

    private void btnGhostedMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGhostedMousePressed
        paintBorder((JRadioButton) evt.getSource(), "Ghosted");
    }//GEN-LAST:event_btnGhostedMousePressed

    private void btnBigHeadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBigHeadMousePressed
        paintBorder((JRadioButton) evt.getSource(), "Big Head");
    }//GEN-LAST:event_btnBigHeadMousePressed

    private void btnBoostMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBoostMousePressed
        paintBorder((JRadioButton) evt.getSource(), "Boost");
    }//GEN-LAST:event_btnBoostMousePressed

    private void btnStickyGooMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStickyGooMousePressed
        paintBorder((JRadioButton) evt.getSource(), "Sticky Goo");
    }//GEN-LAST:event_btnStickyGooMousePressed
   
    private void paintBorder(JRadioButton button, String namePower) {
        this.selectedPower = namePower;
        this.powerList.forEach(p -> p.setBorderPainted(false));
        button.setBorderPainted(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPowers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ViewPowers().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgPower;
    private javax.swing.JRadioButton btnBeachBall;
    private javax.swing.JRadioButton btnBigBumper;
    private javax.swing.JRadioButton btnBigHead;
    private javax.swing.JRadioButton btnBlock;
    private javax.swing.JRadioButton btnBoost;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnFimDeJogo;
    private javax.swing.JRadioButton btnGhosted;
    private javax.swing.JButton btnGol;
    private javax.swing.JRadioButton btnMoveBall;
    private javax.swing.JRadioButton btnMovePlayer;
    private javax.swing.JButton btnPlayer1;
    private javax.swing.JButton btnPlayer2;
    private javax.swing.JRadioButton btnRamp;
    private javax.swing.JRadioButton btnStickyGoo;
    private javax.swing.JRadioButton btnSwapGoals;
    private javax.swing.JButton isGolContra;
    private javax.swing.JButton isSucesso;
    private javax.swing.JButton isUsado;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel txtGolPlayer1;
    private javax.swing.JLabel txtGolPlayer2;
    // End of variables declaration//GEN-END:variables
}
